# Generated by Django 4.2.8 on 2023-12-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockData',
            new_name='JsonModel',
        ),
    ]
